### ISSUE TITLE
Mouse movement/acceleration for horizontal and vertical are way off!

### ISSUE THREAD

**Issue by rdawman** [barry-ran/QtScrcpy#290]
I am not sure how to really explain the problem.

In any FPS games, when you go into aim mode (ex: with right click) the the horizontal movement is fine but the vertical movement is way off...requiring me to lift the mouse and pull/push it again to reach the top/bottom corners.

Changing the mouse sensitivity in game only adjusts the speed for both axis such that when it is adjusted in such a way that the vertical movement is at a good sensitivity, the X axis movement becomes over-sensitive that you could do a 360 degree turn with just a slight flick.

What I'm trying to say is...it would be awesome to have a separate sensitivity value for Vertical and Horizontal speed ratio for mouse movement.[https://paste.pics/A47BD](url)

**Comment by jirehnimes** [comment]
I experienced same issue with CODM as well. Movement is not stable. Even when you're pressing D key it will jump even if the keymap configured is correct. Also, sometimes instead of moving it will move/rotate the view of the screen which shouldn't be even if the offset is lowered. Need a stable fix for the movement especially for FPS games.

**Comment by barry-ran** [comment]
[v1.5.0](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.5.0)
