### ISSUE TITLE
开启之后看不到界面

### ISSUE THREAD

**Issue by liuzeze** [barry-ran/QtScrcpy#34]
![image](https://user-images.githubusercontent.com/16509444/66972897-a7273200-f0c8-11e9-8d65-9c5265178869.png)

**Comment by barry-ran** [comment]
什么手机？录屏可以录到画面吗？控制台详细输出贴一下

**Comment by liuzeze** [comment]
咋录屏?  不过点击窗口右边的 音量 或者开 关屏幕 都会在手机上有效果就是看不到画面 而且 显示画面的部分也不可点击

**Comment by blackcat5** [comment]
我的手机是mate30, 和这兄弟一直看不到，错误是
QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

**Comment by JKXY** [comment]
情况 +1  三星s8,录屏可以录到画面,操作有效，就是无画面输出
start server...
libpng warning: iCCP: known incorrect sRGB profile

AdbProcess::out:[100%] /data/local/tmp/scrcpy-server.jar

AdbProcess::out:G:/soft/QtScrcpy-win64-v1.0.3/scrcpy-server.jar: 1 file pushed. 0.9 MB/s (23362 bytes in 0.026s)

server start finish in 1.422s

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)


*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

    varying vec2 textureOut;        // ???????????????????????????
    uniform sampler2D textureY;     // uniform ??????????????????????????ö???????
    uniform sampler2D textureU;     // sampler2D??2D??????
    uniform sampler2D textureV;     // ????yuv???????????
    void main(void)
    {
        vec3 yuv;
        vec3 rgb;
        // ?????????????textureY??????textureOut??????
        yuv.x = texture2D(textureY, textureOut).r;
        yuv.y = texture2D(textureU, textureOut).r - 0.5;
        yuv.z = texture2D(textureV, textureOut).r - 0.5;
        // ????????rgb
        rgb = mat3(1.0, 1.0, 1.0,
                    0.0, -0.39465, 2.03211,
                    1.13983, -0.58060, 0.0) * yuv;
        // ????????
        gl_FragColor = vec4(rgb, 1.0);
    }

***

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

stop server

success record C:/Users/ComOne_1/Desktop/QtScrcpy_20191028_154014_967.mp4

**Comment by yyyedc** [comment]
同样的问题,操作有效，就是看不到画面，我的手机是realme x2

**Comment by mwmb2** [comment]
我也有这个问题，试过几个不同的手机都一样。我的电脑是三星的上网本，Intel HD Graphics 3000的集成显卡，好像只支持3.0的OpenGL。不知是不是这个原因。

**Comment by barry-ran** [comment]
> 我也有这个问题，试过几个不同的手机都一样。我的电脑是三星的上网本，Intel HD Graphics 3000的集成显卡，好像只支持3.0的OpenGL。不知是不是这个原因。

感谢反馈，应该就是 opengl 3.0的问题了，后面我测试下

**Comment by mwmb2** [comment]
下了新版本，还是同样的问题。

**Comment by barry-ran** [comment]
排查出是opengl 3.0的问题，还没有修复

**Comment by mwmb2** [comment]
收到，感谢及时的回复。希望可以尽快解决这个问题。

**Comment by barry-ran** [comment]
试一下v1.2.1

**Comment by HaoTian22** [comment]
> 试一下v1.2.1

还是不行，我的是mate8
电脑是核显，AID64上显示最高支持openGL 3.1的
OpenGL 3.1	是  (100%)

下面是log
start server...
AdbProcess::out:D:/Program Files/QtScrcpy-win-x64-v1.2.1/scrcpy-server: 1 file pushed. 0.5 MB/s (26142 bytes in 0.054s)

AdbProcess::error:adb.exe: error: more than one device/emulator

adb reverse failed

AdbProcess::out:27183

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

video socket connect to server read device info failed, try again

server start finish in 3.361s

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
ERROR: 0:8: '' : No precision specified for (float)
ERROR: 0:9: '' : No precision specified for (float)
ERROR: 0:11: '' : No precision specified for (float)
ERROR: 0:12: '' : No precision specified for (float)
ERROR: 0:13: '' : No precision specified for (float)


*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#line 1

    varying vec2 textureOut;        // ???????????????
    uniform sampler2D textureY;     // uniform ???????????????????
    uniform sampler2D textureU;     // sampler2D?2D???
    uniform sampler2D textureV;     // ??yuv??????
    void main(void)
    {
        vec3 yuv;
        vec3 rgb;
        // SDL2-2.0.10\src\render\opengl\SDL_shaders_gl.c BT709_SHADER_CONSTANTS
        const vec3 Rcoeff = vec3(1.1644,  0.000,  1.7927);
        const vec3 Gcoeff = vec3(1.1644, -0.2132, -0.5329);
        const vec3 Bcoeff = vec3(1.1644,  2.1124,  0.000);
        // ???????textureY???textureOut???
        yuv.x = texture2D(textureY, textureOut).r;
        yuv.y = texture2D(textureU, textureOut).r - 0.5;
        yuv.z = texture2D(textureV, textureOut).r - 0.5;
        // ?????rgb
        rgb.r = dot(yuv, Rcoeff);
        rgb.g = dot(yuv, Gcoeff);
        rgb.b = dot(yuv, Bcoeff);
        // ?????
        gl_FragColor = vec4(rgb, 1.0);
    }

***

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked

QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

**Comment by barry-ran** [comment]
> > 试一下v1.2.1
> 
> 还是不行，我的是mate8
> 电脑是核显，AID64上显示最高支持openGL 3.1的
> OpenGL 3.1 是 (100%)
> 
> 下面是log
> start server...
> AdbProcess::out:D:/Program Files/QtScrcpy-win-x64-v1.2.1/scrcpy-server: 1 file pushed. 0.5 MB/s (26142 bytes in 0.054s)
> 
> AdbProcess::error:adb.exe: error: more than one device/emulator
> 
> adb reverse failed
> 
> AdbProcess::out:27183
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> video socket connect to server read device info failed, try again
> 
> server start finish in 3.361s
> 
> AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored
> 
> QOpenGLShader::compile(Fragment): ERROR: 0:2: '' : No precision specified for (float)
> ERROR: 0:8: '' : No precision specified for (float)
> ERROR: 0:9: '' : No precision specified for (float)
> ERROR: 0:11: '' : No precision specified for (float)
> ERROR: 0:12: '' : No precision specified for (float)
> ERROR: 0:13: '' : No precision specified for (float)
> 
> *** Problematic Fragment shader source code ***
> #ifdef GL_KHR_blend_equation_advanced
> #extension GL_ARB_fragment_coord_conventions : enable
> #extension GL_KHR_blend_equation_advanced : enable
> #endif
> #line 1
> 
> ```
> varying vec2 textureOut;        // ???????????????
> uniform sampler2D textureY;     // uniform ???????????????????
> uniform sampler2D textureU;     // sampler2D?2D???
> uniform sampler2D textureV;     // ??yuv??????
> void main(void)
> {
>     vec3 yuv;
>     vec3 rgb;
>     // SDL2-2.0.10\src\render\opengl\SDL_shaders_gl.c BT709_SHADER_CONSTANTS
>     const vec3 Rcoeff = vec3(1.1644,  0.000,  1.7927);
>     const vec3 Gcoeff = vec3(1.1644, -0.2132, -0.5329);
>     const vec3 Bcoeff = vec3(1.1644,  2.1124,  0.000);
>     // ???????textureY???textureOut???
>     yuv.x = texture2D(textureY, textureOut).r;
>     yuv.y = texture2D(textureU, textureOut).r - 0.5;
>     yuv.z = texture2D(textureV, textureOut).r - 0.5;
>     // ?????rgb
>     rgb.r = dot(yuv, Rcoeff);
>     rgb.g = dot(yuv, Gcoeff);
>     rgb.b = dot(yuv, Bcoeff);
>     // ?????
>     gl_FragColor = vec4(rgb, 1.0);
> }
> ```
> 
> QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked
> 
> QOpenGLShaderProgram::attributeLocation(vertexIn): shader program is not linked
> 
> QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked
> 
> QOpenGLShaderProgram::attributeLocation(textureIn): shader program is not linked
> 
> QOpenGLShaderProgram::uniformLocation(textureY): shader program is not linked
> 
> QOpenGLShaderProgram::uniformLocation(textureU): shader program is not linked
> 
> QOpenGLShaderProgram::uniformLocation(textureV): shader program is not linked

config.ini里修改下解码方式，改成1试试

**Comment by HaoTian22** [comment]
> config.ini里修改下解码方式，改成1试试

ok，可以了，谢谢

**Comment by mwmb2** [comment]
真的可以了，非常感谢。
